### PR TITLE
Switch to using docker environment for boulder server to reduce converge times

### PR DESCRIPTION
**Pull request by ramereth**
This completely switches how the boulder server is setup to using containers.
This uses the docker compose environment provided by upstream which is more
updated and doesn't require much compiling. This seems to reduce at least two
minutes off running the builds.

Since docker support on CentOS 6 is lacking, this keeps the same deployment
setup as before for that version of the platform. We still have a few hosts that
are using letsencrypt so I thought it was important to keep this support
included.

This also includes improved integration testing which deploys an apache web
server using acme certs to ensure the whole setup works properly. In addition,
it switches from modifying /etc/hosts to using a local dnsmasq server to help
with DNS resolution.

This depends on osuosl-cookbooks/osl-docker#14 being merged first.

### CODE REVIEW

**Comment by ramereth** [comment]
Something to keep in mind, after this is merged I will go through each cookbook that already uses osl-acme to ensure they have an updated Berksfile which includes a pointer to osl-docker which is a new dependency.

**Comment by ramereth** [comment]
[Reduce converge times with osl-acme hosts](https://trello.com/c/7B11gwtp/696-reduce-converge-times-with-osl-acme-hosts)

**Review by eldebrim — APPROVED** [review]

**Comment by eldebrim** [comment]
We'll also need to make a small update to the tests as the output this time is a little different:

New boulder version
```
* Server certificate:
* 	subject: serialNumber=ff913c8d74fa000c871bd63186178c365daf,CN=elinux.org
* 	start date: Feb 21 19:47:50 2018 GMT
* 	expire date: May 22 19:47:50 2018 GMT
* 	common name: elinux.org
* 	issuer: CN=h2ppy h2cker fake CA
```

Old boulder version
```
* Server certificate:
* 	subject: serialNumber=ff9a58770a458357a7d7c411187be7019373,CN=elinux.org
* 	start date: Feb 21 21:08:00 2018 GMT
* 	expire date: May 22 21:08:00 2018 GMT
* 	common name: elinux.org
* 	issuer: CN=happy hacker fake CA
```

**Comment by ramereth** [comment]
@eldebrim yup, I'll make some PRs to update that as well.

**Comment by ramereth** [comment]
!bump major *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a major-level version bump to v2.0.0.  Have a nice day!

**Pull request merged**
